BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task_bertidx.yaml
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
TORCH_GPU_IDS: [0]
TRAINER_NAME: add_lang
GPU_NUMBERS: 1
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: logs/tensorboard_dirs/
CHECKPOINT_FOLDER: logs/checkpoints/
EVAL_CKPT_PATH_DIR: logs/checkpoints/
RESULTS_DIR: logs/eval_results/
RANDOM_ALLOC_SCENE: False
WP_CKPT: ./waypoint_prediction/checkpoints/check_val_best_avg_wayscore
WP_CKPT_LANG: vlnce_baselines/add_lang/waypoint_prediction/checkpoints/check_val_best_avg_wayscore
LANG: attened_lang
save_interval: 2
save_plus: 0

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1

IL:
  epochs: 50
  batch_size: 16
  schedule_ratio: 0.50
  decay_time: 20
  max_traj_len: 20

MODEL:
  policy_name: PolicyViewSelectionVLNBERT
  NUM_ANGLES: 12
  spatial_output: False
  RGB_ENCODER:
    encode_size: 2048
    output_size: 512
  DEPTH_ENCODER:
    encode_size: 128
    output_size: 256
    ddppo_checkpoint: data/pretrained_models/ddppo-models/gibson-2plus-resnet50.pth
  VISUAL_DIM:
    vis_hidden: 768
    directional: 128
  INSTRUCTION_ENCODER:
    bidirectional: True
  LANG_ENCODER:
    type: vlnbert
    lang_checkpoint: logs/checkpoints/cont-cwp-vlnbert-ori/vlnbert_ckpt_best.pth